Add changelog lint cmd
elastic/elastic-agent-changelog-tool pull request #119
Opened 2022-10-28 11:42 UTC by lucianpy

Closes #45

Cherry-pick of `a7d4406` is required. 
PR #116 should be merged first.

- [ ] Replace `changelog_lint` with `changelog lint` using subcommand.

2022-10-28 11:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-119/detail/PR-119/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-119/detail/PR-119/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-119/detail/PR-119/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-119/detail/PR-119/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent-changelog-tool_119.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-10-28T11:32:57.635Z&rangeTo=2022-10-28T11:52:57.635Z&transactionName=BUILD+elastic-agent-changelog-tool-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=0d59c01184e7ef35ae3420cc7b187240&transactionId=d0de0972b4a5230d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-28T11:42:57.635+0000


* Duration: 3 min 41 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 72  |
| Skipped      | 0 |
| Total        | 72   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-31 16:42 UTC, endorama commented
I like the approach, I added a commit that extracts the validators to separate functions, as we need to add tests for them to ensure long term maintainability.

Once that is done this will be good to merge.

2022-11-03 09:00 UTC, endorama requested changes

2022-11-03 09:00 UTC, endorama commented on main.go
> +	rootCmd.AddCommand(cmd.ChangelogLintCmd(appFs))
nit: add this in alphabetical order

2022-11-03 09:04 UTC, lucianpy commented on internal/changelog/linter_test.go
> +func TestValidators(t *testing.T) {
Makes sense, I've seen this way of testing before in Elastic. Any particular scenario where this type of testing would be preferable to breaking them down?

2022-11-03 09:26 UTC, endorama approved these changes

2022-11-03 09:30 UTC, merged