Initial backstage anc buildkite boilerplate
elastic/elastic-agent-changelog-tool pull request #140
Opened 2023-06-15 10:34 UTC by alexsapran

This commit adds the initial boilerplate for initializing the backstage and buildkite resources.

2023-06-15 10:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-140/detail/PR-140/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-140/detail/PR-140/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-140/detail/PR-140/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent-changelog-tool-mbp%2FPR-140/detail/PR-140/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-agent-changelog-tool_140.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-06-15T10:24:20.899Z&rangeTo=2023-06-15T10:44:20.899Z&transactionName=BUILD+elastic-agent-changelog-tool-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=38a93c0f59613d569b722d319c8119d2&transactionId=b89894fafef76f84)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-06-15T10:34:20.899+0000


* Duration: 4 min 13 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 85  |
| Skipped      | 0 |
| Total        | 85   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-06-15 12:37 UTC, jlind23 requested changes

2023-06-15 12:37 UTC, jlind23 commented on catalog-info.yaml
> +  name: elastic-agent-system-metrics
```suggestion
  name: elastic-agent-changelog-tool
```

2023-06-15 14:29 UTC, mrodm commented on catalog-info.yaml
> +  name: elastic-agent-system-metrics
```suggestion
  name: elastic-agent-changelog-tool
  description: Tooling to manage the changelog for beats, Elastic Agent and Fleet Server
```

2023-06-15 14:29 UTC, mrodm commented on catalog-info.yaml
> +      repository: elastic/elastic-agent-changelog-tool
```suggestion
      branch_configuration: "main v0.*"
      repository: elastic/elastic-agent-changelog-tool
```

2023-06-15 14:33 UTC, mrodm requested changes

2023-06-15 14:33 UTC, mrodm commented on catalog-info.yaml
> +        filter_condition: |
```suggestion
        filter_condition: >-
```

2023-06-19 10:05 UTC, endorama commented
Thanks for the contribution! Let me know if you need help in moving this forward (it seems not) but I would love to see it included in Backstage so big :+1: from me!

2023-07-14 14:07 UTC, mrodm commented on .buildkite/pull-requests.json
> +         "build_on_commit": false,
As it is the main pipeline, I would set here these two fields as true

```suggestion
         "set_commit_status": true,
         "build_on_commit": true,
```

2023-07-14 14:18 UTC, mrodm approved these changes
:+1:

2023-07-14 14:59 UTC, merged